version: '3.8'

services:

  db:
    image: mysql:8.0.28
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_USER: user_gestao
      MYSQL_PASSWORD: 123456
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gestao_pedidos_db